sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "6"
  - "7"

cache:
  npm: true
  directories:
  - client/node_modules

before_install:
  - npm install -g npm@latest local-web-server codecov
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - cd client && npm install
  - pip install --user codecov

script:
  # Client
  - npm run lint
  - npm run test
  - ng build --prod --aot
  - cd dist && ws --port 4200&
  - npm run e2e

after_script:
  - codecov
