sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: python
python:
  - 3.6

services:
  - postgresql

cache:
  npm: true
  directories:
    - client/node_modules

before_install:
  - wget http://download.redis.io/releases/redis-4.0.1.tar.gz
  - tar xzf redis-4.0.1.tar.gz
  - cd redis-4.0.1
  - make
  - src/redis-server&
  - export REDIS=redis://localhost:6379/1
  - npm install -g npm@latest local-web-server codecov
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  # Client
  - cd client && npm install

  # Server
  - cd ../server && pip install coverage pycodestyle
  - pip install -r requirements.txt
  - psql -c 'create database server;' -U postgres

script:
  # Client
  - cd ../client && npm run lint
  - npm run test
  - npm run build
  - cd dist && ws --port 4200&
  - npm run e2e

  # Server
  - cd ../server && coverage run --source='.' manage.py test
  - coverage xml
  - pycodestyle --show-source --max-line-length=120 --show-pep8 .

after_script:
  - cd .. && codecov
